# Generated by Django 4.1.7 on 2023-03-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="姓名"),
                ),
                ("age", models.IntegerField(verbose_name="年龄")),
            ],
        ),
    ]
