# Generated by Django 4.1.7 on 2023-03-31 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="序号"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("sex", models.CharField(max_length=50, verbose_name="性别")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("tel", models.CharField(max_length=50, verbose_name="联系方式")),
            ],
        ),
        migrations.CreateModel(
            name="publisher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="出版社编号"
                    ),
                ),
                ("name", models.IntegerField(verbose_name="出版社名称")),
                ("addr", models.CharField(max_length=64, verbose_name="出版社地址")),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="序号"
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="用户名")),
                ("email", models.CharField(max_length=50, verbose_name="邮箱")),
                ("mobile", models.IntegerField(verbose_name="手机号码")),
            ],
        ),
        migrations.CreateModel(
            name="bookInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="序号"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="图书名称")),
                ("ISBN", models.CharField(max_length=50, verbose_name="图书编号")),
                (
                    "translator",
                    models.CharField(default="", max_length=50, verbose_name="译者"),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="出版时间")),
                (
                    "publisher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.publisher",
                    ),
                ),
            ],
        ),
    ]
